name: mypy-lint

on: pull_request

jobs:
  mypy-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh
      - name: Set up Python
        run: uv python install 3.11
      - name: Install project dependencies (including dev deps)
        run: uv sync
      - name: Run mypy check
        run: make mypy
